apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  ingressClassName: nginx

  rules:
    - host: localhost
      http:
        paths:
<<<<<<< HEAD
          - path: /api/?(.*)
=======
          - path: /api(.*)
>>>>>>> 8d74be2 (commit 2)
            pathType: ImplementationSpecific
            backend:
              service:
                name: python-api
                port:
<<<<<<< HEAD
                  number: 80
=======
                  number: 80
>>>>>>> 8d74be2 (commit 2)
