apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

<<<<<<< HEAD
  storageClassName: standard
=======
  storageClassName: standard
>>>>>>> 8d74be2 (commit 2)
