apiVersion: v1
kind: Service
metadata:
  name: redis

spec:
  selector:
    app: redis

  ports:
    - port: 6379
<<<<<<< HEAD
      targetPort: 6379
=======
      targetPort: 6379
>>>>>>> 8d74be2 (commit 2)
