<<<<<<< HEAD
replicaCount: 1
=======
replicaCount: 2
>>>>>>> 8d74be2 (commit 2)

image:
  repository: python-api
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

redis:
  image: redis:7
  port: 6379
  password: redis-123

ingress:
  enabled: true
  host: localhost
<<<<<<< HEAD
  path: /api/?(.*)
=======
  path: /api/?(.*)
>>>>>>> 8d74be2 (commit 2)
